### ISSUE TITLE
A tracked property without an initial value throws error: "...inner.update is not a function"

### ISSUE THREAD

**Issue by christophersansone** [glimmerjs/glimmer.js#205]
Hi there,

I'm upgrading a Glimmer project from 0.7 to 0.13 and found an issue that I can reproduce on the Glimmer Playground.

If I define a tracked property without a default value, such as:

```
@tracked count: number;
// or
@tracked count;
```

... then an exception is thrown when attempting to set the value:

```
Uncaught TypeError: metaFor(...).updatableTagFor(...).inner.update is not a function
```

If the property is given any default value, even `undefined`, then it works as expected.

[Link to the Glimmer Playground reproduction](https://tinyurl.com/y6r79q86)

Is this by design?  This was working in 0.7.  The workaround is obviously to set a default value for every property, but it is unclear that this is a requirement.
